name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '00 22 * * 1-5'
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: ./report/reports/index.html
